### ISSUE TITLE
spark-scala3-encoders issues with spark-sql v. 4.0.0

### ISSUE THREAD

**Issue by alorchenkov** [vincenzobaz/spark-scala3#64]
Hello,

The following code throws an error with `libraryDependencies += "org.apache.spark" %% "spark-sql" % "4.0.0" cross CrossVersion.for3Use2_13`:

```
import scala3encoders.given
    val customerDf = data.select(
      col("Created Date"),
      col("Name"),
      col("Customer Number"),
      col("Customer ID"),
      col("Customer Email Address"),
      col("Customer Account Name"),
      col("Description"),
    ).map(row =>
      (row.getString(0),
        row.getString(1),
        row.getString(2),
        row.getString(3),
        row.getString(4),
        row.getString(5),
        row.getString(6),
        "success"
      )
    )
```
JDK17
Scala 3.3.6
sbt 1.11.0

The error:
```
[info]   java.lang.NoSuchMethodError: 'org.apache.spark.sql.catalyst.encoders.ExpressionEncoder org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$.apply(org.apache.spark.sql.catalyst.expressions.Expression, org.apache.spark.sql.catalyst.expressions.Expression, scala.reflect.ClassTag)'
[info]   at scala3encoders.EncoderDerivation$package$.encoder(EncoderDerivation.scala:22)
```

However, the same code and same configuration work fine when
`libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.5.5" cross CrossVersion.for3Use2_13`

Thanks!

**Comment by alorchenkov** [comment]
Hi @vincenzobaz ,
Thank you for your replies!

I re-run the same tests with the new version 0.3.0:
```
libraryDependencies += "io.github.vincenzobaz" %% "spark-scala3-encoders" % "0.3.0" excludeAll(ExclusionRule(organization = "org.apache.spark"), ExclusionRule(organization = "spark-sql_2.13"))

libraryDependencies += "io.github.vincenzobaz" %% "spark-scala3-udf" % "0.3.0" excludeAll(ExclusionRule(organization = "org.apache.spark"), ExclusionRule(organization = "spark-sql_2.13"))
```

1. It works fine with Spark 3.5.5

`libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.5.5" cross CrossVersion.for3Use2_13`

1. Unfortunately, it still fails with Spark 4.0.0:

`libraryDependencies += "org.apache.spark" %% "spark-sql" % "4.0.0" cross CrossVersion.for3Use2_13`

```
An exception or error caused a run to abort: 'org.apache.spark.sql.catalyst.encoders.ExpressionEncoder org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$.apply(org.apache.spark.sql.catalyst.expressions.Expression, org.apache.spark.sql.catalyst.expressions.Expression, scala.reflect.ClassTag)' 
java.lang.NoSuchMethodError: 'org.apache.spark.sql.catalyst.encoders.ExpressionEncoder org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$.apply(org.apache.spark.sql.catalyst.expressions.Expression, org.apache.spark.sql.catalyst.expressions.Expression, scala.reflect.ClassTag)'
	at scala3encoders.EncoderDerivation$package$.encoder(EncoderDerivation.scala:22)
```

**Comment by vincenzobaz** [comment]
Try with 
> ```
> libraryDependencies += "io.github.vincenzobaz" %% "spark4-scala3-encoders" % "0.3.0" excludeAll(ExclusionRule(organization = "org.apache.spark"), ExclusionRule(organization = "spark-sql_2.13"))
> 
> libraryDependencies += "io.github.vincenzobaz" %% "spark4-scala3-udf" % "0.3.0" excludeAll(ExclusionRule(organization = "org.apache.spark"), ExclusionRule(organization = "spark-sql_2.13"))

**Comment by alorchenkov** [comment]
Hi @vincenzobaz,
Thank you!

No `ExpressionEncoder` errors anymore.
